server:
  port: 8081
spring:
  application:
    name: auth-service
#  config:
#    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  expiration: 1000

application:
  config:
    user-url: http://localhost:8222/api/v1/users