server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/customers/** #to redirect http://localhost:8090 to /api/v1/customers/**
        - id: customers
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/frauds/**
